export const projectList = [
  {
    name: 'angular-docs',
    title: 'Angular Documentation Website',
    description: 'Designing an easy-to-use developer-focused website.',
    image: 'angular-docs.png',
    imageLink: 'https://www.angular.io',
    designSystemsTag: true,
    uxDesignTag: true,
    uiDevelopmentTag: true,
    creativeStrategyTag: true,
    caseStudyAvailable: false
  },
  {
    name: 'surepayroll-onboarding',
    title: 'SurePayroll Onboarding Experience',
    subtitle: 'Redesigning the online customer enrollment experience.',
    description: 'Increasing enrollment conversion.',
    clientName: 'SurePayroll',
    clientDescription: 'SurePayroll is a Paychex Company focused on providing small business owners with easy-to-use online payroll services',
    projectDate: 'Spring - Fall 2018',
    image: 'surepayroll-onboarding.png',
    imageLink: 'https://www.surepayroll.com/',
    designSytemsTag: true,
    uxDesignTag: true,
    uiDevelopmentTag: true,
    designSystemsTag: true,
    caseStudyAvailable: false,
    role: 'UX Lead and Engineer',
    roleTasks: 'user flows, wireframing, visual design, prototyping, design system, front-end development',
    roleDescription: 'I was the lead UX Designer beginning with planning and requirements gathering including on-site strategy meetings with executive leadership and stakeholders, to wireframing, designing and development. I collaborated with SurePayroll\'s subject matter experts and design team, as well as the development team.',
    tools: 'AdobeXD, Adobe Illustrator, Angular, HTML, SCSS',
    projectSummary: 'The goal of this project was to create a new and improved streamlined onboarding experience for SurePayroll\'s small business customers. The primary focus was to increase the conversion rate and update the UI and aesthetics to a more modern look and feel.',
  },
];
